// -*- Mode: Go; indent-tabs-mode: t -*-

/*
 * Copyright 2024 Canonical Ltd.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package cargo_test

import (
	"archive/tar"
	"compress/gzip"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/canonical/fetch-service/inspectors/cargo"
	. "github.com/canonical/fetch-service/inspectors/common"
	"github.com/canonical/fetch-service/inspectors/files"
	"github.com/canonical/fetch-service/metadata"
	"github.com/canonical/fetch-service/metadata/digests"
	"github.com/canonical/fetch-service/metadata/opinions"
	"github.com/gabriel-vasile/mimetype"
	. "gopkg.in/check.v1"
)

var libc_url = "https://static.crates.io:443/crates/libc/0.2.155/download"

// Part of the contents of Cargo.toml for the libc crate
var libc_cargotoml = `# THIS FILE IS AUTOMATICALLY GENERATED BY CARGO
[package]
name = "libc"
version = "0.2.155"
authors = ["The Rust Project Developers", "Another Author"]
build = "build.rs"
exclude = [
    "/ci/*",
    "/.github/*",
    "/.cirrus.yml",
    "/triagebot.toml",
]
autobins = false
autoexamples = false
autotests = false
autobenches = false
description = """
Raw FFI bindings to platform libraries like libc.
"""
license = "MIT OR Apache-2.0"
`

func (s *cargoSuite) TestCargoInspectorID(c *C) {
	ins := cargo.NewCrateInspector()
	c.Assert(ins.ID(), Equals, "cargo.crate")
}

func (s *cargoSuite) TestCargoInspectRequest(c *C) {
	ins := cargo.NewCrateInspector()
	a := metadata.NewArtifact()
	a.CurrentDownload = metadata.Download{URL: libc_url}

	err := ins.InspectRequest(a)
	c.Assert(err, IsNil)

	insp, ok := a.RequestInspection[ins.ID()]
	c.Assert(ok, Equals, true)
	c.Assert(insp.Opinion, Equals, opinions.Unknown)
	c.Assert(insp.Reason, Equals, "unsupported origin")

	c.Assert(a.RequestInspection[ins.ID()].Annotations["package-name"], Equals, "libc")
	c.Assert(a.RequestInspection[ins.ID()].Annotations["package-version"], Equals, "0.2.155")
}

func (s *cargoSuite) TestCargoInspectRequestBadOrigin(c *C) {
	ins := cargo.NewCrateInspector()
	a := metadata.NewArtifact()
	a.CurrentDownload = metadata.Download{URL: "https://bad.origin.io:443/crates/libc/0.2.155/download"}

	err := ins.InspectRequest(a)
	c.Assert(err, IsNil)

	_, ok := a.RequestInspection[ins.ID()]
	c.Assert(ok, Equals, false)
}

func (s *cargoSuite) TestCargoInspectRequestBadSlug(c *C) {
	ins := cargo.NewCrateInspector()
	a := metadata.NewArtifact()
	a.CurrentDownload = metadata.Download{URL: "https://static.crates.io:443/packages/libc/0.2.155/download"}

	err := ins.InspectRequest(a)
	c.Assert(err, IsNil)

	_, ok := a.RequestInspection[ins.ID()]
	c.Assert(ok, Equals, false)
}

func (s *cargoSuite) TestCargoInspectArtifact(c *C) {
	tmp := c.MkDir()
	filename := filepath.Join(tmp, "libc-0.2.155.crate")

	err := createTarball(filename, "libc-0.2.155", libc_cargotoml)
	if err != nil {
		panic(err)
	}

	ins := cargo.NewCrateInspector()
	a := createArtifact(ins)

	f, err := files.OpenArtifactFile(filename)
	c.Assert(err, IsNil)
	defer f.Close()

	err = ins.InspectArtifact(f, a)
	c.Assert(err, IsNil)
	c.Assert(a.Approved(), Equals, true)

	c.Check(a.Metadata.Type, Equals, "application/x.rust.crate")
	c.Check(a.Metadata.Name, Equals, "libc")
	c.Check(a.Metadata.Version, Equals, "0.2.155")
	c.Check(a.Metadata.Vendor, Equals, "")
	c.Check(a.Metadata.Description, Equals, "Raw FFI bindings to platform libraries like libc.")
	c.Check(a.Metadata.Author, Equals, "The Rust Project Developers, Another Author")
	c.Check(a.Metadata.AuthorEmail, Equals, "")
	c.Check(a.Metadata.License, Equals, "MIT OR Apache-2.0")
	c.Assert(a.Approved(), Equals, true)
}

func (s *cargoSuite) TestCargoInspectArtifactNoCargoToml(c *C) {
	tmp := c.MkDir()
	filename := filepath.Join(tmp, "libc-0.2.155.crate")

	err := createTarball(filename, "bad-dir", libc_cargotoml)
	if err != nil {
		panic(err)
	}

	ins := cargo.NewCrateInspector()
	a := createArtifact(ins)

	f, err := files.OpenArtifactFile(filename)
	c.Assert(err, IsNil)
	defer f.Close()

	err = ins.InspectArtifact(f, a)
	c.Assert(err, IsNil)
	c.Assert(a.Approved(), Equals, false)
}

func (s *cargoSuite) TestCargoInspectArtifactBadCargoToml(c *C) {
	tmp := c.MkDir()
	filename := filepath.Join(tmp, "libc-0.2.155.crate")

	bad_toml := strings.Replace(libc_cargotoml, `name = "libc"`, `name = "my-crate"`, 1)

	err := createTarball(filename, "libc-0.2.155", bad_toml)
	if err != nil {
		panic(err)
	}

	ins := cargo.NewCrateInspector()
	a := createArtifact(ins)

	f, err := files.OpenArtifactFile(filename)
	c.Assert(err, IsNil)
	defer f.Close()

	err = ins.InspectArtifact(f, a)
	c.Assert(err, IsNil)
	c.Assert(a.Approved(), Equals, false)
}

func createTarball(filename, subdir, contents string) error {
	archive, err := os.Create(filename)
	if err != nil {
		panic(err)
	}
	defer archive.Close()

	zip_writer := gzip.NewWriter(archive)
	defer zip_writer.Close()
	tar_writer := tar.NewWriter(zip_writer)
	defer tar_writer.Close()

	// Create a tarball with a "Cargo.toml" file inside the libc-0.2.155/ dir
	header := &tar.Header{
		Name: fmt.Sprintf("%s/Cargo.toml", subdir),
		Size: int64(len(contents)),
	}

	err = tar_writer.WriteHeader(header)
	if err != nil {
		return err
	}

	_, err = tar_writer.Write([]byte(contents))
	if err != nil {
		return err
	}

	return nil
}

func createArtifact(ins Inspector) *metadata.Artifact {
	h, _ := digests.NewSha1Digest("42962163ae017f7c2ffbcb79e4268e9c6250b8d9") //nolint: errcheck

	a := metadata.NewArtifact()
	a.Metadata.Type = "application/gzip"
	a.Metadata.Sha1 = h
	a.MimeType = mimetype.Lookup("application/gzip")
	a.CurrentDownload.URL = libc_url
	a.RequestInspection[ins.ID()] = &Inspection{
		Opinion:     opinions.Pending,
		Reason:      "some reason",
		Annotations: Annotation{"package-name": "libc", "package-version": "0.2.155"},
	}

	return a
}
