version: "2"
linters:
  default: none
  enable:
    - errcheck
    - gocyclo
    # - gosec
    - govet
    - ineffassign
    - nakedret
    - staticcheck
    - unused
  settings:
    errcheck:
      check-blank: true
    gocyclo:
      min-complexity: 15
    staticcheck:
      checks:
        - all
        - "-ST1005" # Accept capitalized error message
    nakedret:
      max-func-lines: 20