#!/bin/bash

set -e
CMD="$1"

exec 3>&1
exec 1>&2

allocate() {
	if [ -z "$CI" ]; then
		echo "This backend is intended to be used only in CI systems."
		exit 1
	fi
	sudo sed -i "s|#PasswordAuthentication yes|PasswordAuthentication yes|g" /etc/ssh/sshd_config
	sudo sed -i "s|KbdInteractiveAuthentication no|KbdInteractiveAuthentication yes|g" /etc/ssh/sshd_config
	sudo rm -f /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
	sudo systemctl daemon-reload
	sudo systemctl restart ssh

	sudo useradd spread -s /bin/bash -m || true
	echo "spread:spread" | sudo chpasswd || true
	echo 'spread ALL=(ALL) NOPASSWD:ALL ' | sudo tee /etc/sudoers.d/99-spread-user || true

	# Print the instance address to stdout
	echo localhost >&3
}

discard() {
	true
}

case "$CMD" in
allocate)
	allocate
	;;
discard)
	discard
	;;
esac
