#!/bin/bash

set -ex
CMD="$1"

exec 3>&1
exec 1>&2

allocate() {
	name=$(echo "$SPREAD_SYSTEM" | tr '[:punct:]' -)
	system=$(echo "$SPREAD_SYSTEM" | tr / -)
	if [[ "$system" =~ ^ubuntu- ]]; then
		image="ubuntu:${system#ubuntu-}"
	else
		image="images:$(echo "$system" | tr - /)"
	fi

	VM_NAME="${VM_NAME:-spread-${name}-${RANDOM}}"
	DISK="${DISK:-20}"
	CPU="${CPU:-4}"
	MEM="${MEM:-8}"

	lxc launch --vm \
		"${image}" \
		"${VM_NAME}" \
		-c cloud-init.user-data="$(cat tests/spread/cloud-config.yaml)" \
		-c user.user-data="$(cat tests/spread/cloud-config.yaml)" \
		-c limits.cpu="${CPU}" \
		-c limits.memory="${MEM}GiB" \
		-d root,size="${DISK}GiB"

	lxc exec "${VM_NAME}" -- cloud-init status --long --wait || :

	# Wait for the spread user
	while ! lxc exec "${VM_NAME}" -- id -u spread &>/dev/null; do sleep 0.5; done
	lxc exec "${VM_NAME}" -- rm -f /etc/ssh/sshd_config.d/60-cloudimg-settings.conf

	# Print the instance address to stdout
	ADDR=""
	while [ -z "$ADDR" ]; do ADDR=$(lxc ls -f csv | grep "^${VM_NAME}" | cut -d"," -f3 | cut -d" " -f1); done
	echo "$ADDR" 1>&3
}

discard() {
	instance_name="$(lxc ls -f csv | grep "$SPREAD_SYSTEM_ADDRESS" | cut -f1 -d",")"
	lxc delete -f "$instance_name"
}

case "$CMD" in
allocate)
	allocate
	;;
discard)
	discard
	;;
esac
