name: fetch-service # you probably want to 'snapcraft register <name>'
version: 'git'
base: core24
summary: Canonical Fetch Service
description: |
  The fetch service is a tool to mediate network access when executing
  craft tools.

grade: stable
confinement: strict
adopt-info: fetch

platforms:
  amd64:
  arm64:

apps:
  # licensecheck app here for debugging.
  licensecheck:
    command: usr/bin/licensecheck
    plugs:
      - home
  fetchd:
    command: bin/fetch-service.sh
    daemon: simple
    refresh-mode: endure
    plugs:
      - network-bind
    install-mode: disable
  fetch-service:  # Just run the fetch service as a command.
    command: bin/fetch
    plugs:
      - network-bind
      - home
  fetchctl:  # Fetch service configuration tool
    command: bin/fetchctl
    plugs:
      - home

environment:
  # PERLLIB needed for licensecheck
  PERLLIB: $SNAP/lib/perl5:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/perl/5.34:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/perl5/5.34:$SNAP/usr/share/perl/5.34:$SNAP/usr/share/perl5:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/perl-base:$SNAP/usr/share/licensecheck

parts:
  licensecheck:
    plugin: nil
    stage-packages:
      - licensecheck
      - git
  fetch:
    build-packages:
      - git
    build-snaps:
      - go
    plugin: go
    source: .
    override-build: |
      rm -f version/version.txt
      go generate ./...
      craftctl default
      craftctl set version=$(cat version/version.txt)
  config:
    plugin: dump
    source: snap/local/conf
    organize:
      '*': conf/
  service-runner:
    plugin: dump
    source: .
    source-subdir: snap/local
  fetchctl:
    plugin: nil
    override-prime: |
      craftctl default
      ln -s fetch bin/fetchctl
