name: Sync to Launchpad

on:
  push:
concurrency:
  group: ${{ github.workflow }}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: main # Always check out the main branch since we're going to push everything.
      - name: Sync to Launchpad
        run: |
          git fetch --all
          git pull --all
          git remote add launchpad https://${{ secrets.LP_USER }}:${{ secrets.LP_TOKEN }}@git.launchpad.net/fetch-service
          git push --mirror --force launchpad
          git push --tags --force launchpad
