name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies
        run: |
          set -x
          sudo apt update
          sudo apt install -y cpanminus gcc make
          sudo cpanm --notest https://cpan.metacpan.org/authors/id/J/JO/JONASS/Regexp-Pattern-License-v3.9.3.tar.gz  # 3.11.1 doesn't work!
          sudo cpanm --notest https://cpan.metacpan.org/authors/id/P/PE/PEVANS/Syntax-Keyword-Try-0.27.tar.gz
          sudo cpanm --notest https://cpan.metacpan.org/authors/id/J/JO/JONASS/App-Licensecheck-v3.3.9.tar.gz
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      - name: Build code
        run: |
          go build ./cmd/fetch
      - name: Run unit tests
        run: |
          go test -race ./...
