name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  linters:
    runs-on: [self-hosted, Linux]  # Pretty much any self-hosted Linux runner, base independent
    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: true
      - name: Generate version
        run: |
          go generate ./version
      - name: Run Linters
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: '-c .github/.golangci.yaml'
      - name: Run shellcheck
        run: |
          make lint-shellcheck

  unit-tests:
    runs-on: [noble, amd64]
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y licensecheck
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'
      - name: Generate version
        run: |
          go generate ./version
      - name: Build code
        run: |
          go build ./cmd/fetch
      - name: Run unit tests
        run: |
          go test -race ./...

  snap-build:
    runs-on: [noble, amd64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Build snap
        uses: canonical/action-build@v1
        id: snap
      - name: Upload snap artifact
        uses: actions/upload-artifact@v5
        with:
          name: snap
          path: ${{ steps.snap.outputs.snap }}

  snap-test:
    strategy:
      matrix:
        os:
          - [jammy, amd64]
          - [noble, amd64]
    # needs:  # Re-enable this once we can test a prebuilt snap
    #   - snap-build
    runs-on: ${{ matrix.os }}
    permissions:
      # Ensure GITHUB_TOKEN has enough permissions to clone the repo in spread tests.
      contents: read
    steps:
      - name: Install dependencies
        run: |
          sudo snap install snapcraft --classic --channel=latest/edge
          sudo snap install lxd  # remove once we can test a pre-built snap
          lxd init --auto
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      # Uncomment this when we're testing a prebuilt snap.
      # - name: Download snap artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: snap
      - name: Run spread tests
        env:
          # GH_FETCH_SERVICE_TOKEN is used in some spread tests to clone the fetch-service
          # repository itself.
          GH_FETCH_SERVICE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          STORE_MACAROON: ${{ secrets.STORE_MACAROON }}
        run: |
          snapcraft test --verbose
