name: TICS

on:
  push:
    branches:
      - main
      # to easy test changes to the workflow
      - work/tiobe**

jobs:
  CI:
    runs-on: [self-hosted, reactive, amd64, tiobe, noble]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.9

      - name: Install dependencies
        run: |
          echo "::group::apt-get update"
          sudo apt-get update
          echo "::endgroup::"
          echo "::group::apt-get install..."
          sudo apt-get install -y licensecheck
          echo "::endgroup::"
          echo "::group::staticcheck"
          go install honnef.co/go/tools/cmd/staticcheck@latest
          echo "::endgroup::"
          echo "::group::gocov"
          go install github.com/axw/gocov/gocov@latest
          go install github.com/AlekSi/gocov-xml@latest
          echo "::endgroup::"

      - name: Build code
        run: |
          go generate ./...
          go build ./cmd/fetch

      - name: Run unit tests
        run: |
          mkdir .coverage
          go test -coverprofile .coverage/cover.out ./...
          cd .coverage
          ~/go/bin/gocov convert cover.out > coverage.json
          ~/go/bin/gocov-xml < coverage.json > coverage-go.xml

      - name: Run TICS analysis
        uses: tiobe/tics-github-action@v3
        with:
          mode: qserver
          project: fetch-service
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=GoProjects
          branchdir: ${{ github.workspace }}
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true
