#!/bin/bash -e
# Initialise the snap upon install

# Create file spool
rm -Rf "${SNAP_COMMON}/spool"
mkdir -m 0700 "${SNAP_COMMON}/spool"

# Initial ACL rules
mkdir -p "${SNAP_DATA}/conf"
cat <<EOF >"${SNAP_DATA}/conf/acl.yaml"
http-proxy:
  policy: allow
  rules:
    - dst: [
      ]
      access: deny
EOF
