#!/bin/bash -e

CONF_DIR="${SNAP_DATA}/conf"
CA_CERT_DIR="${SNAP_DATA}/certs"

mkdir -p "$CONF_DIR"

# Remove unchanged default configuration files
if [ -f "${CONF_DIR}/acl.yaml" ]; then
	digest=$(sha256sum "${CONF_DIR}/acl.yaml" | cut -f1 -d' ' | tr -d '\n')
	if [ "$digest" == "a7c4075e9231df17f00fc708a1e5fce3b996a4fd25b66f1bdc42cf8cbc077221" ]; then
		rm -f "${CONF_DIR}/acl.yaml"
	fi
fi

if [ -f "${CONF_DIR}/inspectors.yaml" ]; then
	digest=$(sha256sum "${CONF_DIR}/inspectors.yaml" | cut -f1 -d' ' | tr -d '\n')
	if [ "$digest" == "62e323393507073ddd1a4f924e8014a1114d71caea033ee65198ebcfbfd305e0" ]; then
		rm -f "${CONF_DIR}/inspectors.yaml"
	fi
fi

# Create a CA certificate if it doesn't exist
if [ ! -f "$CA_CERT_DIR/ca.pem" ]; then
	mkdir -p "$CA_CERT_DIR"
	chmod 0700 "$CA_CERT_DIR"
	(
		cd "$CA_CERT_DIR"
		openssl genrsa -aes256 -passout pass:1 -out ca.key.pem 4096
		openssl rsa -passin pass:1 -in ca.key.pem -out ca.key.pem.tmp
		mv ca.key.pem.tmp ca.key.pem
		openssl req -subj "/CN=root@localhost" -key ca.key.pem -new -x509 -days 7300 -sha256 -extensions v3_ca -out ca.pem
	)
	cp "$CA_CERT_DIR/ca.pem" "${SNAP_DATA}/local-ca.crt"
fi
