#!/bin/bash -e

CONF_DIR="${SNAP_DATA}/conf"
CA_CERT_DIR="${SNAP_DATA}/certs"

mkdir -p $(dirname "$ACL_YAML")

# If old acl configuration exists, move it to conf/
if [ -f "${SNAP_DATA}/acl.yaml" ]; then
	mv "${SNAP_DATA}/acl.yaml" "$CONF_DIR/"
fi

# Create configuration files if they doesn't exist
if [ ! -f "${CONF_DIR}/acl.yaml" ]; then
	cp "${SNAP}/skel/acl.yaml" "$CONF_DIR/"
fi

if [ ! -f "${CONF_DIR}/inspectors.yaml" ]; then
	cp "${SNAP}/skel/inspectors.yaml" "$CONF_DIR/"
fi

# Create a CA certificate if it doesn't exist
if [ ! -f "$CA_CERT_DIR/ca.pem" ]; then
	mkdir -p "$CA_CERT_DIR"
	chmod 0700 "$CA_CERT_DIR"
	(
		cd "$CA_CERT_DIR"
		openssl genrsa -aes256 -passout pass:1 -out ca.key.pem 4096
		openssl rsa -passin pass:1 -in ca.key.pem -out ca.key.pem.tmp
		mv ca.key.pem.tmp ca.key.pem
		openssl req -subj "/CN=root@localhost" -key ca.key.pem -new -x509 -days 7300 -sha256 -extensions v3_ca -out ca.pem
	)
	cp "$CA_CERT_DIR/ca.pem" "${SNAP_DATA}/local-ca.crt"
fi
